name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18]
        python-version: ["3.11"]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Frontend install/build/test
        working-directory: frontend
        run: |
          npm ci
          npm run lint
          npm run build
          npm test -- --ci --watchAll=false || true
      - name: Server install/build/test
        working-directory: server
        run: |
          npm ci
          npm run build
          npm test -- --ci --watchAll=false || true
      - name: ML-service install/test
        working-directory: ml-service
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pytest -q || true
