name: Deploy
on:
  workflow_dispatch:
  push:
    branches: [ main ]
jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker images
        run: |
          docker build -t prismiq-server ./server
          docker build -t prismiq-ml ./ml-service
      - name: (Optional) Push to registry
        run: |
          echo "Configure registry login and docker push here"
